// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEtOtcL5GeVxoB9zl1UUXr2ig8nQJJXUo',
    appId: '1:710059881140:web:d07ec815ff42958c8f5de1',
    messagingSenderId: '710059881140',
    projectId: 'amato-sweet-store',
    authDomain: 'amato-sweet-store.firebaseapp.com',
    storageBucket: 'amato-sweet-store.firebasestorage.app',
    measurementId: 'G-T72EESS054',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHZ-ZvHP9wDNsW4eDMzY28GbT1y_K43N0',
    appId: '1:710059881140:android:dad44ca1aabd02c68f5de1',
    messagingSenderId: '710059881140',
    projectId: 'amato-sweet-store',
    storageBucket: 'amato-sweet-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6us8A-9HbL5qA3QGhN_XQatSIP6tmiTM',
    appId: '1:710059881140:ios:0b5bdd85ec62a09e8f5de1',
    messagingSenderId: '710059881140',
    projectId: 'amato-sweet-store',
    storageBucket: 'amato-sweet-store.firebasestorage.app',
    iosBundleId: 'com.example.mainAmato',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6us8A-9HbL5qA3QGhN_XQatSIP6tmiTM',
    appId: '1:710059881140:ios:0b5bdd85ec62a09e8f5de1',
    messagingSenderId: '710059881140',
    projectId: 'amato-sweet-store',
    storageBucket: 'amato-sweet-store.firebasestorage.app',
    iosBundleId: 'com.example.mainAmato',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEtOtcL5GeVxoB9zl1UUXr2ig8nQJJXUo',
    appId: '1:710059881140:web:30cd712ae748e7518f5de1',
    messagingSenderId: '710059881140',
    projectId: 'amato-sweet-store',
    authDomain: 'amato-sweet-store.firebaseapp.com',
    storageBucket: 'amato-sweet-store.firebasestorage.app',
    measurementId: 'G-DSDGF2Z3Q5',
  );
}
